#!/usr/bin/env bash
#a Bash script that displays To infinity and beyond indefinitely
#I am invincible!!! when receiving a SIGTERM signal
#With a sleep 2 in between each iteration

msg()
{
    echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
