#!/usr/bin/env bash
#This bash script displays the time for 12 hours and 59 minutes
h="0"
while [ "$h" -le 12 ]
do
    echo "Hour: $h";
    ((h++))
    m="0"
    while [ "$m" -le 59 ]
    do
	echo "$m";
	((m++))
    done
done
